### ISSUE TITLE
Return Response object from Execution Module 

### ISSUE THREAD

**Issue by tsa87** [googleinterns/step81-2020#13]
Well we need to do better than this, does it mean that we will need a response action that generates the message for the user? We will face more and more problems like this when we expand the functionality of the bot.

_Originally posted by @lipczak-g in https://github.com/googleinterns/step81-2020/pull/10_

**Comment by miasya** [comment]
Created CardResponse.java

**Comment by miasya** [comment]
Created CardResponse.java
