### ISSUE TITLE
Bot message returned is above original user message in hangouts chat UI

### ISSUE THREAD

**Issue by miasya** [googleinterns/step81-2020#2]

**Comment by SydneyCaulfeild** [comment]
"This is a known issue, see tracking bug b/137663185.  If you are creating the async response via the chat API before responding with the empty response to the event in the synchronous flow, you may be able to decrease the likelihood that the issue appears by returning an empty response for the bot event earlier if possible, and then kicking off the async logic afterwards.  There will still be the potential for a race condition, but it may help if you find that this is occurring consistently." - Jessica Battrick
