### ISSUE TITLE
Customize the response message from the bot through the UI.

### ISSUE THREAD

**Issue by SydneyCaulfeild** [googleinterns/step81-2020#27]
L78: The response message should be customizable through UI as well.
_Originally posted by @lipczak-g in https://github.com/googleinterns/step81-2020/pull/23#discussion_r457805318_

The execute() function in MacroExecutionModuleImplementation.java currently returns a hard-coded message "Successfully executed". Users should be able to customize this message through the UI.

**Comment by SydneyCaulfeild** [comment]
@tsa87 is this something you can look into with Flutter?

**Comment by tsa87** [comment]
Sure, I will assign myself.

**Comment by tsa87** [comment]
Close in favor of returning cards
